site_name: Heiqihuolin website
site_url: #http://www.wanggsh.cn
site_author: Wangguangshuai
site_description: >-
  Show me!
# Repository
#repo_name: 
#repo_url: 

# Copyright
copyright: wanggsh

# Configuration
theme:
  name: material
  logo: assets/website_icon1.png
  favicon: assets/website_icon1.png
  custom_dir: material/overrides
  features:
    #- announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # # - content.tabs.link
    - content.tooltips
    #- header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: #white
      accent: #white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocs-jupyter:
      include_source: True

# Hooks
#hooks:
#  - material/.overrides/hooks/translations.py

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GuangShuaiWang


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

# Page tree
nav:
  - Home: index.md

  - Learn: 
    - Overview : Learn/learn_homepage.md
    - z2m-pytorch :
      - chacpter00 : "Learn/z2m-pytorch/00_pytorch_foundmental.ipynb"
      - chacpter01 : "Learn/z2m-pytorch/01_pytorch_workflow.ipynb"
    - MKdoc: "Learn/How-build-statical-website.md"

